# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poop_name', models.CharField(max_length=200)),
                ('poop_type', models.CharField(max_length=200)),
            ],
        ),
    ]
